"""
Event and alert models.
Supports the full event lifecycle from generation to resolution.
"""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Severity(str, Enum):
    """Alert severity levels."""
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertType(str, Enum):
    """Types of alerts the system can generate."""
    ANOMALY_DETECTED = "anomaly_detected"
    FAULT_CLASSIFIED = "fault_classified"
    THRESHOLD_EXCEEDED = "threshold_exceeded"
    RUL_WARNING = "rul_warning"
    DEVICE_OFFLINE = "device_offline"
    SENSOR_DEGRADED = "sensor_degraded"
    UNKNOWN_FAULT = "unknown_fault"
    MAINTENANCE_DUE = "maintenance_due"
    SHUTDOWN_RECOMMENDED = "shutdown_recommended"
    EDGE_RESOURCE_WARNING = "edge_resource_warning"
    ESCALATION = "escalation"


class EventType(str, Enum):
    """Types of events in the system."""
    TELEMETRY_READING = "telemetry_reading"
    INFERENCE_COMPLETE = "inference_complete"
    MONITORING_SNAPSHOT = "monitoring_snapshot"
    FAULT_EVENT = "fault_event"
    ANOMALY_EVENT = "anomaly_event"
    UNKNOWN_FAULT_DETECTION = "unknown_fault_detection"
    PREDICTIVE_ALERT = "predictive_alert"
    DEVICE_REGISTERED = "device_registered"
    DEVICE_HEARTBEAT = "device_heartbeat"
    MAINTENANCE_EVENT = "maintenance_event"
    SYSTEM_EVENT = "system_event"


class Alert(BaseModel):
    """An alert generated by the platform."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    timestamp: int = Field(default_factory=lambda: int(time.time()))
    device_id: str
    severity: Severity
    alert_type: AlertType
    message: str
    metadata: dict[str, Any] = Field(default_factory=dict)
    acknowledged: bool = False
    resolved: bool = False
    resolved_at: int | None = None
    escalated: bool = False
    suppressed: bool = False
    dedup_key: str | None = None

    def deduplication_key(self) -> str:
        """Generate deduplication key for this alert."""
        if self.dedup_key:
            return self.dedup_key
        return f"{self.device_id}:{self.alert_type.value}:{self.severity.value}"


class Event(BaseModel):
    """A system event for logging and correlation."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    timestamp: int = Field(default_factory=lambda: int(time.time()))
    event_type: EventType
    device_id: str | None = None
    source: str = "platform"
    data: dict[str, Any] = Field(default_factory=dict)
    correlation_id: str | None = None


class MaintenanceRecommendation(BaseModel):
    """A maintenance action recommendation."""
    timestamp: int = Field(default_factory=lambda: int(time.time()))
    device_id: str
    priority: Severity
    action: str
    reason: str
    estimated_rul_hours: float | None = None
    fault_class: str | None = None
    confidence: float = 0.0
